
@startsalt tela_doc
{
  {+
    **Acompanhar contratos (secretaria)**
    --
    {
      Pesquisar Aluno: | "                        "
      [Buscar]
    }
    --
    {#
       Aluno | Contrato | Status | Ação
       Lucas Jesus | Estágio - Tech Corp | **Em análise** | [Detalhes]
       Caio Ximenes | Estágio - Soft Inc | **Aprovado** | [Detalhes]
       Otto balestrini | Estagio - cisco   | **Pendente** | [Detalhes]
    }
    --
    {
      **Histórico de Movimentações (Selecionado):**
      - 10/04: Recebido pela Secretaria
      - 12/04: Aguardando assinatura do Coordenador
      - 15/04: Em análise técnica (Documentação OK)
      [Fazer Download do Documento]
    }
  }
  ---
  {+
    **Acompanhar contratos (Aluno)**
    --
    {#
       Contrato | Status | Ação
       Estágio - Tech Corp | **Em análise** | [Detalhes]
    }
    --
    {
      **Histórico de Movimentações (Selecionado):**
      - 10/04: Recebido pela Secretaria
      { [Baixar documento] | [Reenviar documento] } 
    }
  }
}
@endsalt