@startsalt
{+
  [ Documento Expandido ]
  --
  Histórico de Empresa: 
  "Athena Educação - Regular"
  --
  Mensagem de aviso:
  "Justificativa em caso de reprovação"
  --
  [ Validar ] 
  [ Reprovar ]
}
@endsalt