@startuml

|Aluno|
start
:Aluno aprovado em estágio
entra em contato com a Secretaria;

|Secretaria|
:Envia contrato para aluno repassar à empresa;

|Empresa|
:Preenche o contrato;

|Secretaria|
:Valida o contrato;

|Carreiras|
:Guarda para controle interno;

|Aluno|
:Realiza o período de estágio;

|Coordenação|
:Compara período de estágio
com o contrato;
:Valida as horas;

stop

@enduml