@startmindmap

* Validação
** Horas
***Atividades
****Compatibilidade com curso
****Compatibilidade com cargo
***Quantidade de horas
****Compatibilidade com curso
****Compatibilidade com cargo
****Compatibilidade com contrato

@endmindmap