@startsalt
{+
  Contrato: Termo de Compromisso
  Status: Reprovado
  --
  Justificativa:
  "Falta assinatura da empresa"
  --
  [ Contrato Expandido ]
  --
  [ Fazer download ] 
  [ Reenviar ] 
  [ Reportar erro ]
}
@endsalt