@startmindmap
*Gestão de estágios
**Gestão de contratos
***Validação de contratos
***Gestão de documentos
***Versionamento dos contratos
***Reputação da empresa
**Validação do período de estágio
***Verificação de área de conhecimento
***Verificação de carga horária
**Gestão de alunos
***Cadastro de alunos
***Gestão de documentos     
***Versionamento dos documentos
@endmindmap