# Generated by Django 6.0.4 on 2026-05-28 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_email_institucional_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='matricula',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='historicoavaliacaocontrato',
            name='data_avaliacao',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 18, 5, 57, 939203, tzinfo=datetime.timezone.utc), verbose_name='Data de avaliação'),
        ),
        migrations.AlterField(
            model_name='historicoavaliacaorelatorio',
            name='data_avaliacao',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 18, 5, 57, 939203, tzinfo=datetime.timezone.utc), verbose_name='Data de avaliação'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_upload',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 18, 5, 57, 939203, tzinfo=datetime.timezone.utc), verbose_name='Data de upload'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='matricula',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Matrícula'),
        ),
    ]
