# Generated by Django 6.0.4 on 2026-05-28 19:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_secretaria_aluno_curso_aluno_periodo_contrato_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoavaliacaocontrato',
            name='data_avaliacao',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 19, 25, 13, 133251, tzinfo=datetime.timezone.utc), verbose_name='Data de avaliação'),
        ),
        migrations.AlterField(
            model_name='historicoavaliacaorelatorio',
            name='data_avaliacao',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 19, 25, 13, 133251, tzinfo=datetime.timezone.utc), verbose_name='Data de avaliação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='matricula_aluno',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_aluno', to='core.aluno', to_field='matricula'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('pendente_analise', 'Pendente de Análise'), ('reprovado', 'Reprovado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='pendente_analise', max_length=20),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_upload',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 19, 25, 13, 133251, tzinfo=datetime.timezone.utc), verbose_name='Data de upload'),
        ),
    ]
