# Generated by Django 6.0.4 on 2026-05-28 19:04

import core.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unicidade_cpf_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[core.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='historicoavaliacaocontrato',
            name='data_avaliacao',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 19, 4, 22, 951528, tzinfo=datetime.timezone.utc), verbose_name='Data de avaliação'),
        ),
        migrations.AlterField(
            model_name='historicoavaliacaorelatorio',
            name='data_avaliacao',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 19, 4, 22, 951528, tzinfo=datetime.timezone.utc), verbose_name='Data de avaliação'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_upload',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 19, 4, 22, 951528, tzinfo=datetime.timezone.utc), verbose_name='Data de upload'),
        ),
    ]
