@startuml
title Casos de Uso - Pacote Secretaria
left to right direction
skinparam packageStyle rectangle

actor "Secretaria" as sec

rectangle "Plataforma de Estágios" {

        package "Secretaria" {
            usecase "Fazer Login" as login
            usecase "Anexar Documento" as enviar
            
            usecase "Validar Documento" as validarDoc
            usecase "Analisar Documento" as analisarDoc
            usecase "Acompanhar Status do Processo" as acompanhar
            usecase "Pesquisar alunos" as pesquisarAlunos
            usecase "Cadastrar aluno" as cadastrarAluno
            usecase "Pesquisar Status da empresa" as pesquisarStatus
            usecase "Iniciar Processo" as iniciar
            usecase "Enviar Relatório" as enviarHoras
            
            usecase "Reprovar Documento com Justificativa" as reprovarJustificativa
            usecase "Encerrar processo" as encerrar
            usecase "Fazer Download do Documento" as download
        }

}

sec --> validarDoc
sec --> analisarDoc
sec --> acompanhar
sec --> pesquisarAlunos
sec --> cadastrarAluno
sec --> pesquisarStatus
sec --> iniciar
sec --> enviarHoras

validarDoc ..> login : <<include>>
analisarDoc ..> login : <<include>>
acompanhar ..> login : <<include>>
pesquisarAlunos ..> login : <<include>>
cadastrarAluno ..> login : <<include>>
pesquisarStatus ..> login : <<include>>
iniciar ..> login : <<include>>
enviarHoras ..> login : <<include>>

iniciar ..> enviar : <<include>>
enviarHoras ..> enviar : <<include>>

validarDoc <.. reprovarJustificativa : <<extend>>
acompanhar <.. encerrar : <<extend>>
acompanhar <.. download : <<extend>>
analisarDoc <.. download : <<extend>>

@enduml