@startsalt
{+
  Documento: Termo de Compromisso
  Status: Reprovado
  --
  Justificativa:
  "Falta assinatura da empresa"
  --
  [ Documento Expandido ]
  --
  [ Fazer download ] 
  [ Reenviar ] 
  [ Reportar erro ]
}
@endsalt