@startuml

' --- Estilos ---
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

' --- Enums ---
enum Veredito {
    APROVADO
    REPROVADO
}

' --- Classes Relevantes ---
abstract class Usuario {
    # matricula : string
    # nome : string
    # email : string
    # senha : string
    # unidade : Unidade
}

class Coordenador extends Usuario {
    - areaId : int
}

class Area {
    - id : int
    - nome : string
}

class Processo {
    - id : int
    - nome_empresa : string
    - data_criacao : Date
    - status : StatusProcesso
    - matricula_aluno : int
    + nome_processo() : string
}

class Relatorio {
}

abstract class HistoricoAvaliacao {
    - id : int
    - observacoes : string
    - data_avaliacao : Date
    - veredito : Veredito
}

class HistoricoAvaliacaoRelatorio extends HistoricoAvaliacao {
    - avaliador : int
    - relatorio_id : int
}

' --- Relacionamentos ---
Coordenador "1" -- "1" Area
Coordenador "1" -- "0..*" Processo : valida >
Coordenador "1" -- "0..*" HistoricoAvaliacaoRelatorio : avalia >
Relatorio "1" -- "0..1" HistoricoAvaliacaoRelatorio : possui >

@enduml
