@startuml

' --- Estilos ---
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

' --- Enums ---
enum StatusProcesso {
    ABERTO
    EM_ANALISE_SECRETARIA
    EM_ANALISE_COORDENACAO
    PENDENTE_AJUSTE
    APROVADO
    REPROVADO
    CONCLUIDO
    CANCELADO
}

' --- Classes de Processo e Documentação ---
class Processo {
   - id : int
   - data_criacao : Date
   - status : StatusProcesso
   - matricula_aluno : int
   + atualizarStatus(novoStatus : StatusProcesso)
   + validarContrato(aprovado : bool, justificativa : string)
}

class Contrato {
    - id : int
    - arquivo : string
    - data_upload : Date
    - cnpj_empresa : string
    - nome_empresa : string
    - data_inicio : Date
    - data_termino : Date
    - apolice_seguro : string
    - plano_atividade : bool
    - assinatura_aluno : bool
    - assinatura_empresa : bool
    - assinatura_faculdade : bool
    - processoId : int
}

class Relatorio {
    - processoId : int
    - relatorioId : int
    - nomeArquivo : string
    - dataUpload : DateTime
    - horasTrabalhadas : int
    - periodoReferencia : string
    - aprovadoPelaEmpresa : bool
}

' --- Relacionamentos de Processo ---
Processo "1" *-- "1..*" Contrato : contém >
Processo "1" *-- "0..*" Relatorio : contém >
Processo "0..*" -- "1" StatusProcesso : possui >

@enduml
