@startuml

' --- Estilos ---
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

' --- Classes Relevantes ---
abstract class Usuario {
    ' # matricula : int
    ' # nome : string
    ' # email : string
    ' # senha : string
    ' + login() : bool
}

class Coordenacao extends Usuario {
    ' - area : Area
    ' + validarEstagio(processo : Processo, aprovado : bool, justificativa : string)
}

class Area {
}

class Processo {
}

' --- Relacionamentos ---
Coordenacao "1" -- "1" Area
Coordenacao "1" -- "0..*" Processo : valida >

@enduml
