@startuml

' --- Estilos ---
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

' --- Classes Relevantes ---
abstract class Usuario {
    # matricula : string
    # nome : string
    # email : string
    # senha : string
    # unidade : Unidade
}

class Aluno extends Usuario {
    - cpf : string
    - is_ativo : bool
    - periodo : Periodo
    - cursoId : int
}

class Curso {
    - id : int
    - nome : string
    - areaId : int
}

enum Periodo {
    PRIMEIRO, SEGUNDO, TERCEIRO, QUARTO, QUINTO, SEXTO, SETIMO, OITAVO, NONO, DECIMO
}

class Processo {
    - id : int
    - nome_empresa : string
    - data_criacao : Date
    - status : StatusProcesso
    - matricula_aluno : FK<Aluno>
    + nome_processo() : string
}

class Contrato {
    - id : int
    - arquivo : string
    - data_upload : Date
    - cnpj_empresa : string
    - nome_empresa : string
    - data_inicio : Date
    - data_termino : Date
    - apolice_seguro : string
    - plano_atividade : bool
    - assinatura_aluno : bool
    - assinatura_empresa : bool
    - assinatura_faculdade : bool
    - processoId : int
    - status : StatusContrato
    + nome_contrato() : string
}

class Relatorio {
    - id : int
    - processo_id : int
    - arquivo : string
    - data_upload : Date
    - horas_trabalhadas : int
    - data_inicio : Date
    - data_termino : Date
    - status : StatusRelatorio
}

' --- Relacionamentos ---
Aluno "0..*" -- "1" Curso
Aluno "0..*" -- "1" Periodo
Aluno "1" -- "0..1" Processo : possui >
Processo "1" *-- "1..*" Contrato : contém >
Processo "1" *-- "0..*" Relatorio : contém >

@enduml
