@startuml

' --- Estilos ---
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

' --- Enums ---
enum Periodo {
    PRIMEIRO, SEGUNDO, TERCEIRO, QUARTO, QUINTO, SEXTO, SETIMO, OITAVO, NONO, DECIMO
}

' --- Classes da Estrutura Acadêmica ---
class Aluno {
    - matricula : string
    - nome : string
    - email : string
    - senha : string
    - unidade : Unidade
    - cpf : string
    - is_ativo : bool
    - periodo : Periodo
    - cursoId : int
}

class Curso {
    - id : int
    - nome : string
    - areaId : int
}

class Area {
    - id : int
    - nome : string
}

class Coordenador {
    - matricula : string
    - nome : string
    - email : string
    - senha : string
    - unidade : Unidade
    - areaId : int
}

' --- Relacionamentos ---
' Um aluno pertence a um curso e período
Aluno "0..*" -- "1" Curso
Aluno "0..*" -- "1" Periodo

' Hierarquia de Curso e Área
Area "1" -- "0..*" Curso
Coordenador "1" -- "1" Area

@enduml
