@startuml

' --- Estilos ---
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

' --- Enums ---
enum StatusProcesso {
    ABERTO
    PENDENTE
    REPROVADO
    CONCLUIDO
    CANCELADO
}

enum StatusContrato {
    PENDENTE
    EM_ANALISE_SECRETARIA
    APROVADO
    REPROVADO
}

enum StatusRelatorio {
    PENDENTE
    EM_ANALISE_COORDENACAO
    APROVADO
    REPROVADO
}

enum Unidade {
    BARRA
    BOTAFOGO
}

enum Periodo {
    PRIMEIRO, SEGUNDO, TERCEIRO, QUARTO, QUINTO, SEXTO, SETIMO, OITAVO, NONO, DECIMO
}

enum TipoUsuario {
    ALUNO
    SECRETARIA
    COORDENACAO
    CARREIRAS
}

' --- Classes Principais ---

abstract class Usuario {
    # matricula : string
    # nome : string
    # email : string
    # senha : string
    # unidade : Unidade
}

class Aluno extends Usuario {
    - cpf : string
    - is_ativo : bool
    - periodo : Periodo
    - cursoId : int
}

class Secretaria extends Usuario {
}

class Coordenador extends Usuario {
    - areaId : int
}

class Processo {
    - id : int
    - nome_empresa : string
    - data_criacao : Date
    - status : StatusProcesso
    - matricula_aluno : int
    + nome_processo() : string
}

class Contrato {
    - id : int
    - arquivo : string
    - data_upload : Date
    - cnpj_empresa : string
    - nome_empresa : string
    - data_inicio : Date
    - data_termino : Date
    - apolice_seguro : string
    - plano_atividade : bool
    - assinatura_aluno : bool
    - assinatura_empresa : bool
    - assinatura_faculdade : bool
    - processoId : int
    - status : StatusContrato
    + nome_contrato() : string
}

class Relatorio {
    - id : int
    - processo_id : int
    - arquivo : string
    - data_upload : Date
    - horas_trabalhadas : int
    - data_inicio : Date
    - data_termino : Date
    - status : StatusRelatorio
}

class Curso {
    - id : int
    - nome : string
    - areaId : int
}

class Area {
    - id : int
    - nome : string
}

' --- Relacionamentos ---

' Um aluno pertence a um curso e período
Aluno "0..*" -- "1" Curso
Aluno "0..*" -- "1" Periodo

' Hierarquia de Curso e Área
Area "1" -- "0..*" Curso
Coordenador "1" -- "1" Area

' Relacionamento de Processo
Aluno "1" -- "0..1" Processo : possui >
Secretaria "1" -- "0..*" Processo : audita >
Coordenador "1" -- "0..*" Processo : valida >

Processo "1" *-- "1..*" Contrato : contém >
Processo "1" *-- "0..*" Relatorio : contém >
Processo "0..*" -- "1" StatusProcesso : possui >

@enduml
