@startuml

' --- Estilos ---
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

' --- Classes Relevantes ---
abstract class Usuario {
    # matricula : string
    # nome : string
    # email : string
    # senha : string
    # unidade : Unidade
}

class Coordenador extends Usuario {
    - areaId : int
}

class Area {
    - id : int
    - nome : string
}

class Processo {
    - id : int
    - nome_empresa : string
    - data_criacao : Date
    - status : StatusProcesso
    - matricula_aluno : FK<Aluno>
    + nome_processo() : string
}

' --- Relacionamentos ---
Coordenador "1" -- "1" Area
Coordenador "1" -- "0..*" Processo : valida >

@enduml
