@startmindmap




*Secretaria
**Gestão de contratos
***Validação de contratos
***Gestão de documentos
***Versionamento dos contratos
**Gestão de alunos
***Cadastro de alunos
***Gestão de documentos     
***Versionamento dos documentos
*Carreiras
**Reputação da empresa
**Gestão de ofertas de vagas
*Coordenação
**Validação do período de estágio


@endmindmap